alert_distance: 10
attraction_strength: 0.01
axes_max: 1500
axes_min: -500
flock_size: 50
formation_flying_distance: 100
formation_flying_strength: 0.125
frame_interval: 50
frame_number: !!python/tuple
- 50
lower_position_limit: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - &id001 !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 2
  - &id002 !!python/object/apply:numpy.dtype
    args:
    - i4
    - 0
    - 1
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    Pv7//ywBAAA=
lower_velocity_limit: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 2
  - *id002
  - false
  - !!binary |
    AAAAAOz///8=
upper_position_limit: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 2
  - *id002
  - false
  - !!binary |
    MgAAAFgCAAA=
upper_velocity_limit: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 2
  - *id002
  - false
  - !!binary |
    CgAAABQAAAA=
